# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1493d133baff94921756fdfa578b2420505c49afbea225ac877bbb872b946701c646e96374357ab653f9d755191bb549699156a42940dc624f1c07a69f65fd32

test:
  secret_key_base: 7ff5cebcdd5d7d4a15882290ec9cac88d71e7f651af218efe5cb0c0309d6ff2d43171a47f385cebddc5893abef0baa6c38ef56fab7d72e5f9f9359d77f194caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
